### ISSUE TITLE
ES: Use _source filtering to reduce attributes selected from query

### ISSUE THREAD

**Issue by atombender** [sanity-io/gradient#223]
Currently we ask for either all attributes or no attributes. But if a query asks for `*{foo, bar}`, we can use `_source` filtering to pick just those two.

**Comment by simen** [comment]
Can we actually do that? Technically the properties we store in an indexable fashion in ES is potentially severely transformed in order to support our queries, they do not have status as being bona fide gold-standard representations of the content. For this we actually store the document in its entirety within ES. Picking some properties directly from the index seems brittle and dangerous, no?

I'm thinking this is perhaps an old issue past its use-by date?
