### ISSUE TITLE
This query somehow does not work using a parameter to in a limit-offset clause

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#359]
```
"*[is ""movie"" && releaseDate.utc > ""2016-01-01""][0..$limit]{
title,
""cm"":castMembers[0..$limit]{
  person{
name
  }}}"
```

Must investigate

**Comment by erikgrinaker** [comment]
There are multiple reasons for this. Ultimately, it is because the `RangeLiteral` is given the `$limit` parameter as a `float64`, and silently fails on non-`int` boundaries. It receives a `float64` because:

1. `httputils.ExtractGQLParams()` uses `json.Unmarshal()` to parse the value, which returns `float64` for any number - we need to explicitly check if the input had a decimal point and discard the fractional part.

2. `protofy.DoInterface()` turns any numeric value into a `float64`, e.g. the GRPC server loses type information from the HTTP layer. Why do we do this?

Additionally, I think we should change the `RangeLiteral` members `Start` and `End` to be `int` rather than `interface{}`, since all places that use these fields explicitly check that the values are `int` anyway.

**Comment by simen** [comment]
But since float64 correctly models all 32 bit integers, we could just cast it to an integer potentially making sure the fractional part is < 0.0001, no? This would not be totally semantically insane, since the JS/JSON universe we relate to generally don't deal in integers.

**Comment by erikgrinaker** [comment]
Yes, we could cast it to an integer in the `RangeLiteral`. However, I think the bigger issue is that the GRPC layer is completely unable to determine if the user provided `3.0` or `3`, which has downstream effects like this one.

**Comment by simen** [comment]
Yeah, but JSON semantics don't discern between 3.0 and 3 since JS doesn't.

**Comment by erikgrinaker** [comment]
Talked to Simen offline: from what I understand it's been agreed to only use `float64` for numeric values throughout Gradient.
