### ISSUE TITLE
Can't query on booleans?

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#418]
Given the following document:

```js
{
  "_createdAt": "2017-03-02T18:23:32+01:00",
  "_id": "product-1049901",
  "_rev": "po5o4q-gba-i7y-d1s-kow9z7qdz",
  "_type": "product",
  "_updatedAt": "2017-03-24T16:36:11+01:00",
  "eco": true,
  "abv": 13,
  "acid": 6,
  "ageLimit": 18,
  "aroma": "Sval og fokusert aroma preget av modent eple, sitrus og urter, hint av smør og nøtt.",
  "averageRating": 0.9090909090909091,
  "barcode": 3760094051599,
  "bioDynamic": false,
  "color": "Middels dyp strågul.",
  "containerSize": 0.75,
  "containerType": "Glass",
  "deliveryTime": "0000030190",
  "distributor": {
    "_ref": "distributor-30190",
    "_type": "reference",
    "_weak": true
  },
  "district": {
    "_ref": "region-frankrike_burgund",
    "_type": "reference",
    "_weak": true
  },
  "expiredDate": "2010-05-03",
  "fairTrade": false,
  "foodPairing": [
    {
      "_key": "pair-C",
      "_ref": "foodPairingC",
      "_type": "reference",
      "_weak": true
    },
    {
      "_key": "pair-B",
      "_ref": "foodPairingB",
      "_type": "reference",
      "_weak": true
    },
    {
      "_key": "pair-D",
      "_ref": "foodPairingD",
      "_type": "reference",
      "_weak": true
    }
  ],
  "freshness": 75,
  "fullness": 67,
  "gluten": false,
  "image": {
    "_type": "image",
    "asset": {
      "_ref": "image-nsX1icWQk2mhZ7jC3cqNNAMh",
      "_weak": true
    }
  },
  "kosher": false,
  "mainCategory": {
    "_ref": "category-hvitvin",
    "_type": "reference",
    "_weak": true
  },
  "mainCountry": {
    "_ref": "region-frankrike",
    "_type": "reference",
    "_weak": true
  },
  "mainProducer": {
    "_ref": "brand-vincent_girardin",
    "_type": "reference",
    "_weak": true
  },
  "method": "Tradisjonell vinifikasjonsteknikk, tankmodnet før tapping. 75%",
  "name": "Bourgogne Chardonnay Terroir Noble 2013",
  "newProduct": false,
  "price": 192,
  "pricePerLiter": 256,
  "productSelection": "Basisutvalget",
  "rawMaterial": [
    {
      "id": "088",
      "name": "Chardonnay",
      "percentage": 100
    }
  ],
  "status": "active",
  "storable": "Drikkeklar nå, men kan også lagres",
  "storeCategory": "Butikkategori 3",
  "subDistrict": {
    "_ref": "region-frankrike_burgund_bourgogne",
    "_type": "reference",
    "_weak": true
  },
  "summary": "",
  "sweetness": 8,
  "taste": "Ung og sval, preg av moden frukt, eple, sitrus, smør og nøtt. Ettersmak med god lengde.",
  "url": "https://www.vinmonopolet.no/Producenter/Vincent-Girardin/Girardin-Bourgogne-Chardonnay-Terroir-Noble-2013/p/1049901",
  "vintage": 2013,
  "wholesaler": {
    "_ref": "wholesaler-moestue_grape_selections_as",
    "_type": "reference",
    "_weak": true
  }
}
```

When I query for `*[eco == true]` or `*[gluten == false]`, I am not getting any results.
`*[!gluten]` doesn't work either. If I query for a non-boolean value, I get the expected result: 
`*[vintage == 2013]`

The namespace has around 20 000 documents, and I expect each of the boolean queries would return ~2000-10000 results. Setting a limit to 5 items does not yield any difference.

**Comment by rexxars** [comment]
This doesn't seem to happen on a different namespace with less documents.

**Comment by atombender** [comment]
Can you see what the Elasticsearch query is? Can you disable the query optimization (@simen knows how)?

**Comment by erikgrinaker** [comment]
I can reproduce this with a local data set. Gradient runs an ES query with no filters, returning the first 100 out of 30999 matches:

```json
{"_source":{"excludes":[],"includes":["doc"]},"from":0,"query":{"constant_score":{"filter":{"match_all":{}}}},"size":100,"sort":[{"_uid":{"order":"asc"}}]}
```

Gradient then runs another query to retrieve the next page, but this returns 0 documents since Gradient sets `"size":0`:

```json
{"_source":{"excludes":[],"includes":["doc"]},"from":100,"query":{"constant_score":{"filter":{"match_all":{}}}},"size":0,"sort":[{"_uid":{"order":"asc"}}]}
```

Gradient then stops paginating, since ES did not return any documents. Since none of the first 100 documents have `eco:true`, Gradient returns an empty result.

Disabling query optimization (by commenting out `plan = planopt.Optimize(plan)`) seems to fix the ES pagination issue, since it now uses `"size":100` for the second query. Gradient then keeps running queries until reaching `"from":10000`, at which point ES errors out due to pagination limits.

Thus, there are two distinct bugs here: boolean expressions are not included in the ES query at all, and the plan optimizer breaks ES pagination. Will investigate.

**Comment by atombender** [comment]
Good research! This one was dangerous, surprised it's not caused any other problems. It was only by accident that it affected boolean queries specifically.

It turns out the optimizer would apply the limit to the Elasticsearch results, and filtering the results would happen memory (which would happen because boolean comparisons were not recognized as something that could "pushed down" to the Elasticsearch level) _after_ the limit was applied. So the default limit is 100; it would fetch 100 results, filter them by the specified constraint, and then stop. The fix makes sure that the limit doesn't cross the filter.
