### ISSUE TITLE
Subtly different sematics for booleans when embedded?

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#533]
Performed this query:

```
*[_type=='project' && images[].allowFullHeight]
```

Which matched no documents, while this worked as expected:

```
*[_type=='project' && images[].allowFullHeight == true]
```

Do we have some special sauce enabling boolean flags to be stated without the equality, and does this break down when the flag is embedded like that?

**Comment by atombender** [comment]
We've discussed this before, and decided that we eventually want to have booleans work like this, so that you don't need to do `b == true`. However, `images[].allowFullHeight` returns an array and will never match `true`. You need something like `defined(images[allowFullHeight == true])`.

**Comment by simen** [comment]
Well it works. It is analog to `body[].children[].text match "banana"`, so should work according to the semantics we promote for full text search across embedded objects.

**Comment by atombender** [comment]
No, that's because we define `match(array, text)`, so that works by accident. `==` only works for arrays on the LHS if the RHS is an array.

The correct expression is probably `defined(body[].children[text match "banana"])`.

(We talked about supporting just `body[].children[text match "banana"]` and coercing it to a boolean if it stands alone, but I don't think we're there yet.)

**Comment by atombender** [comment]
Actually, it is supported. `*[body[].children[text match "banana"]]` will work. However, it is currently not optimized into an Elasticsearch query.

**Comment by atombender** [comment]
And `*[images[].allowFullHeight == true]` should not work. That's the real bug. It's being translated into the wrong query.

**Comment by atombender** [comment]
This is actually #374.
