### ISSUE TITLE
Ordering of arrays seems arbitrary

### ISSUE THREAD

**Issue by erikgrinaker** [sanity-io/gradient#592]
Consider:

```
documents:
- id: "[1, 2, 3]"
  _type: "order-array"
  value: [1, 2, 3]
- id: "[1, 2, a]"
  _type: "order-array"
  value: [1, 2, "a"]
- id: "[3, 2, 1]"
  _type: "order-array"
  value: [3, 2, 1]

gradient>    [
      *[_type=="order-array"]|order(value asc)[].value,
      *[_type=="order-array"]|order(value desc)[].value,
    ]

[
  [[1,2,"a"], [1,2,3], [3,2,1]],
  [[1,2,3], [3,2,1], [1,2,"a"]],
]
```

The first result should order letters after numbers, while the second does not seem to order the result at all.

**Comment by simen** [comment]
The real error here is `[]` being allowed in ids?

`order` cannot order arrays based on primitive values since there is no "this" operator. In this example order basically orders the objects returned on the entire contents of the arrays. What you want to write here is `*[...].value|order(@ asc)` except you can't. You need to wrap your values in objects to be able to address the values in the order statement: `[{a: 1}, {a: 2}, {a: 'a'}] | order(a asc)`

**Comment by erikgrinaker** [comment]
Ah, there's a typo - I'm using `id`, not `_id`. Either way, the query only looks at `value` (the arrays), not IDs. Let's say I have a collection of documents with an attribute `value`, which contains all sorts of datatypes (numbers, strings, arrays, etc) - we need to be able to order on this attribute.

However, ordering of arrays and objects is non-trivial (see discussion in #564), so we may just have to say that their order is undefined (i.e. random).

**Comment by simen** [comment]
We don't sort objects by array contents. I don't know how that would even work. We would have to hash them in some unholy sortable manner

**Comment by atombender** [comment]
I suggest we close this. Ordering array values (e.g. `[[1], [2]] | order`) seems like an unnecessary thing to support.

**Comment by erikgrinaker** [comment]
We just need to specify the behavior when sorting arrays. Saying that the order is undefined (e.g. random) seems like the most sensible option.

**Comment by atombender** [comment]
👍
